export const translations = {
    es: {
        heroTitle: "Luis Fernando",
        heroRole: "Ingeniero de Software Senior",
        heroDesc: "Especialista en arquitecturas escalables y soluciones web innovadoras para el mercado global.",
        navProjects: "Proyectos",
        navExperience: "Experiencia",
        btnContact: "Contacto",
        downloadCV: "Descargar CV",
        availableForRemoteProjects: "Disponible para Proyectos Remotos",
        terminalTitle: "Carga exitosa: Senior Software Engineer",
        terminalLocation: "Ubicación: Colima, MX",
        terminalFocus: "Enfoque: Scalable Digital Projects",
        terminalStatus: "Status: Ready to innovate",
        stackAndExpertise: "Tecnologías y Experiencia",
        coreDevelopment: "Desarrollo Principal",
        coreDevelopmentDesc: 'Experiencia sólida en el ciclo completo de desarrollo, desde la arquitectura hasta el despliegue.',
        implementationOfAIN8NRAGAndMCPServers: 'Implementación de IA-N8N-RAG y MCP Servers.',
        DisciplinaYRitmoConSalsaEstiloNewYork: 'Disciplina y ritmo con Salsa Estilo New York.',
        projectsHighImpact: 'Proyectos de Alto Impacto',
        OMA_v2_Architecture: 'Re-arquitectura cloud-native migrando sistemas legados a un ecosistema moderno de React y microservicios para optimizar decisiones de flete.',
        CPP_Architecture: 'Diseñé e implementé un sistema centralizado de gestión de facturación desde cero, optimizando el ciclo de facturación de principio a fin para clientes corporativos.',
        viewAllProjects: 'Ver todo los proyectos',
        certifications: 'Certificaciones',
        certificationsDesc: 'Formación continua y validación de aptitudes',
        projectHistory: 'Historial de proyectos',
        projectHistoryDesc: 'Explora mi trayectoria técnica desde 2012',
    },
    en: {
        heroTitle: "Luis Fernando",
        heroRole: "Senior Software Engineer",
        heroDesc: "Specializing in scalable architectures and innovative web solutions for the global market.",
        navProjects: "Projects",
        navExperience: "Experience",
        btnContact: "Contact",
        downloadCV: "Download CV",
        availableForRemoteProjects: "Available for Remote Projects",
        terminalTitle: "Upload successful: Senior Software Engineer",
        terminalLocation: "Location: Colima, MX",
        terminalFocus: "Focus: Scalable Digital Projects",
        terminalStatus: "Status: Ready to innovate",
        stackAndExpertise: "Stack & Expertise",
        coreDevelopment: "Core Development",
        coreDevelopmentDesc: 'Solid experience in the complete development cycle, from architecture to deployment.',
        implementationOfAIN8NRAGAndMCPServers: 'Implementation of IA-N8N-RAG and MCP Servers.',
        DisciplinaYRitmoConSalsaEstiloNewYork: 'Discipline and rhythm with New York Style Salsa.',
        projectsHighImpact: 'High Impact Projects',
        OMA_v2_Architecture: 'Cloud-native re-architecture migrating legacy systems to a modern ecosystem of React and microservices to optimize freight decisions.',
        CPP_Architecture: 'Architected and deployed a centralized Invoicing Management System from the ground up, streamlining the end-to-end billing lifecycle for corporate clients',
        viewAllProjects: 'View all projects',
        certifications: 'Certifications',
        certificationsDesc: 'Continuous training and skills validation',
        projectHistory: 'Project History',
        projectHistoryDesc: 'Explore my technical trajectory since 2012',
    }
};